import argparse
import math
import numpy as np


def cordic_reference(y: int, x: int, data_width: int) -> int:
    """Bit-exact reference for cordic_atan2.

    Matches the output convention:
        angle = round(atan2(y, x) * 2^(DATA_WIDTH-2) / pi)
    Saturated to signed DATA_WIDTH range.
    """
    angle_rad = math.atan2(y, x)              # in [-pi, +pi]
    scale = (1 << (data_width - 2)) / math.pi
    scaled = round(angle_rad * scale)

    # Saturate to signed DATA_WIDTH range
    max_val = (1 << (data_width - 1)) - 1
    min_val = -(1 << (data_width - 1))
    return max(min_val, min(max_val, scaled))


def gen_vectors(n_random: int, seed: int, data_width: int):
    """Generate test vectors. Returns list of (x, y, expected_angle)."""
    rng = np.random.default_rng(seed)

    max_val = (1 << (data_width - 1)) - 1
    min_val = -(1 << (data_width - 1))

    vectors = []

    # Edge cases: axes and 45-degree points
    edge_cases = [
        # (y, x, description)
        (0, max_val,    "positive x axis"),     # angle = 0
        (max_val, 0,    "positive y axis"),     # angle = +pi/2
        (0, min_val,    "negative x axis"),     # angle = +/-pi
        (min_val, 0,    "negative y axis"),     # angle = -pi/2
        (0, 0,          "origin"),              # angle = 0 (mathematically undefined, atan2 returns 0)

        # 45-degree points in each quadrant
        (max_val, max_val,    "Q1 45deg"),      # angle = +pi/4
        (max_val, min_val + 1, "Q2 135deg"),    # angle = +3*pi/4
        (min_val, min_val + 1, "Q3 -135deg"),   # angle = -3*pi/4
        (min_val, max_val,     "Q4 -45deg"),    # angle = -pi/4

        # Small magnitude (test scale) Just Noise, not needed as test
        #(1, 1,          "tiny Q1"),
        #(-1, 1,         "tiny Q4"),
        #(1, -1,         "tiny Q2"),
        #(-1, -1,        "tiny Q3"),

        # Large magnitude
        (max_val // 2, max_val,  "moderate Q1"),
        (max_val, max_val // 2,  "moderate Q1 b"),
    ]

    for y, x, _desc in edge_cases:
        angle = cordic_reference(y, x, data_width)
        vectors.append((x, y, angle))

    # Random vectors
    for _ in range(n_random):
        x = int(rng.integers(min_val, max_val + 1))
        y = int(rng.integers(min_val, max_val + 1))
        angle = cordic_reference(y, x, data_width)
        vectors.append((x, y, angle))

    return vectors


def write_vector_file(path: str, vectors, data_width: int):
    """Write vectors as hex. Field width = ceil(DATA_WIDTH/4) hex chars."""
    hex_chars = (data_width + 3) // 4

    with open(path, 'w') as f:
        for x, y, angle in vectors:
            # Convert signed values to two's complement hex of the right width
            mask = (1 << data_width) - 1
            x_u     = x & mask
            y_u     = y & mask
            angle_u = angle & mask

            line = (
                f"{x_u:0{hex_chars}x} "
                f"{y_u:0{hex_chars}x} "
                f"{angle_u:0{hex_chars}x}"
            )
            f.write(line + "\n")


def write_params_pkg(path: str, n_vectors: int, data_width: int, iterations: int, default_tolerance = 32):
    """Compute a reasonable tolerance based on iteration count.

    CORDIC produces ~ITERATIONS bits of angle precision. At wider DATA_WIDTH
    than ITERATIONS, the lower bits are noise. Tolerance is the worst-case
    error of CORDIC at this iteration count, expressed in output-scale units.

    At iteration N, residual angle is ~2^-N radians. In the output scale
    (where pi maps to 2^(DATA_WIDTH-2)), this is:
        tolerance_ticks = (2^-N) * (2^(DATA_WIDTH-2) / pi)
                        = 2^(DATA_WIDTH-2-N) / pi
                        ~= 2^(DATA_WIDTH - N) / 12       (since pi ~= 3.14)
    Plus a small safety factor for rounding.
    """
    if iterations >= data_width - 1:
        # Iterations match or exceed data width: precision is data-path-limited
        # Allow 4 ULPs for rounding noise across the pipeline
        tolerance = default_tolerance
    else:
        # Iterations are the limiting factor
        # Use a slightly generous bound: 2^(DATA_WIDTH - ITERATIONS) ticks
        # (the divide-by-pi makes this conservative)
        tolerance = max(default_tolerance, 1 << (data_width - iterations))

    content = f"""-- AUTO-GENERATED by cordic_atan2_generator.py. DO NOT EDIT BY HAND.

library ieee;
use ieee.std_logic_1164.all;

package cordic_test_params_pkg is
    constant TEST_N_VECTORS : natural := {n_vectors};
    constant TEST_DATA_WIDTH : natural := {data_width};
    constant TEST_ITERATIONS : natural := {iterations};
    constant TEST_TOLERANCE  : natural := {tolerance};
end package;
"""
    with open(path, 'w') as f:
        f.write(content)


def main():
    parser = argparse.ArgumentParser(
        description="Generate test vectors for cordic_atan2.vhd"
    )
    parser.add_argument("-n", "--num-random", type=int, default=10000)
    parser.add_argument("-s", "--seed", type=int, default=0)
    parser.add_argument("-w", "--data-width", type=int, default=16, help="DATA_WIDTH for the CORDIC under test (default: 16)")
    parser.add_argument("-i", "--iterations", type=int, default=16, help="ITERATIONS of the CORDIC under test (default: 16)")
    args = parser.parse_args()
    
    if args.iterations > args.data_width:
        print(f"Note: ITERATIONS ({args.iterations}) is well beyond the useful "
            f"limit (~{args.data_width}). Iterations past ~{args.data_width} are "
            f"no-op pipeline stages (LUT value rounds to 0), adding latency "
            f"and LUTs but no precision.")  
    
    print(f"created LUT_Table")
    scale = (1 << (args.data_width - 2)) / math.pi
    #for i in range(args.iterations):
    #    lut_val = round(math.atan(2**(-i)) * scale)
    #    print(f"  ATAN_LUT[{i}] = {lut_val}")
    lut_val = round(math.atan(2**(-args.iterations)) * scale)
    print(f"First ommited ATAN_LUT[{args.iterations}] = {lut_val}")
    print(f"if not 0, there will be precision loss")

    vectors = gen_vectors(args.num_random, args.seed, args.data_width)
    write_vector_file("cordic_vectors.hex", vectors, args.data_width)
    write_params_pkg("cordic_test_params_pkg.vhd", len(vectors), args.data_width, args.iterations)

    n_edge = len(vectors) - args.num_random
    print(f"Generated {len(vectors)} vectors ({n_edge} edge cases + "
          f"{args.num_random} random)")
    print(f"  DATA_WIDTH = {args.data_width}, ITERATIONS = {args.iterations}")
    print(f"  Vector file: cordic_vectors.hex")
    print(f"  Params file: cordic_test_params_pkg.vhd")


if __name__ == "__main__":
    main()