import argparse
import numpy as np


HALF_PATCH_SIZE = 15
PATCH_SIZE = 31


def build_umax():
    """Match ORB-SLAM3's u_max construction exactly."""
    hp2 = HALF_PATCH_SIZE ** 2
    vmax = int(np.floor(HALF_PATCH_SIZE * np.sqrt(2.0) / 2.0 + 1.0))
    vmin = int(np.ceil(HALF_PATCH_SIZE * np.sqrt(2.0) / 2.0))

    umax = [0] * (HALF_PATCH_SIZE + 1)
    for v in range(vmax + 1):
        umax[v] = int(round(np.sqrt(hp2 - v * v)))

    v0 = 0
    for v in range(HALF_PATCH_SIZE, vmin - 1, -1):
        while umax[v0] == umax[v0 + 1]:
            v0 += 1
        umax[v] = v0
        v0 += 1

    return umax


U_MAX = build_umax()


def compute_moments(patch: np.ndarray):
    """Bit-exact reference matching ORB-SLAM3's IC_Angle().

    patch: 31x31 uint8 array, indexed as patch[row, col].
    The center is at patch[15, 15].

    Returns (m_10, m_01) as Python ints (no scaling, no atan2).
    """
    assert patch.shape == (PATCH_SIZE, PATCH_SIZE)
    cr = HALF_PATCH_SIZE  # 15

    m_10 = 0
    m_01 = 0

    # Center row (v=0)
    for u in range(-HALF_PATCH_SIZE, HALF_PATCH_SIZE + 1):
        m_10 += u * int(patch[cr, cr + u])

    # Row pairs (v=1..15)
    for v in range(1, HALF_PATCH_SIZE + 1):
        d = U_MAX[v]
        v_sum = 0
        for u in range(-d, d + 1):
            val_plus  = int(patch[cr + v, cr + u])
            val_minus = int(patch[cr - v, cr + u])
            v_sum += (val_plus - val_minus)
            m_10  += u * (val_plus + val_minus)
        m_01 += v * v_sum

    return m_10, m_01


def gen_edge_cases():
    """Hand-checkable patches with known expected outputs."""
    cases = []

    # 1. All zeros
    p = np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    cases.append(("all_zeros", p))

    # 2. All 128 (uniform)
    p = np.full((PATCH_SIZE, PATCH_SIZE), 128, dtype=np.uint8)
    cases.append(("uniform_128", p))

    # 3. Only [v=0, u=+5] = 100
    p = np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    p[15, 15 + 5] = 100
    cases.append(("single_center_pos_u", p))

    # 4. Only [v=0, u=-5] = 100
    p = np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    p[15, 15 - 5] = 100
    cases.append(("single_center_neg_u", p))

    # 5. Only [v=+5, u=0] = 100
    p = np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    p[15 + 5, 15] = 100
    cases.append(("single_pos_v", p))

    # 6. Only [v=-5, u=0] = 100
    p = np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    p[15 - 5, 15] = 100
    cases.append(("single_neg_v", p))

    # 7. Only [v=+5, u=+3] = 100
    p = np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    p[15 + 5, 15 + 3] = 100
    cases.append(("single_corner", p))

    # 8. Pixel outside circular mask: [v=15, u=+10] = 100
    # u_max[15] = 3, so u=+10 must be excluded -> moments are 0
    p = np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    p[15 + 15, 15 + 10] = 100
    cases.append(("outside_mask", p))

    # 9. Pixel at exact mask boundary: [v=15, u=+3] = 100
    # u_max[15] = 3, so u=+3 IS included -> moments nonzero
    p = np.zeros((PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
    p[15 + 15, 15 + 3] = 100
    cases.append(("at_mask_boundary", p))

    # 10. All-max patch (stress test for accumulator widths)
    p = np.full((PATCH_SIZE, PATCH_SIZE), 255, dtype=np.uint8)
    cases.append(("all_255", p))

    return cases


def write_vector_file(path, patches_with_moments):
    """Write patches and expected moments to a hex file.

    Format per line:
      p[0,0] p[0,1] ... p[0,30] p[1,0] ... p[30,30] m_10_hex m_01_hex
    Patch pixels are 2 hex chars each (961 pixels total).
    Moments are 6 hex chars each (24-bit signed, two's complement).
    """
    with open(path, 'w') as f:
        for patch, m_10, m_01 in patches_with_moments:
            parts = []
            for row in range(PATCH_SIZE):
                for col in range(PATCH_SIZE):
                    parts.append(f"{int(patch[row, col]):02x}")

            # Convert signed moments to 24-bit two's complement
            m_10_u = m_10 & 0xFFFFFF
            m_01_u = m_01 & 0xFFFFFF
            parts.append(f"{m_10_u:06x}")
            parts.append(f"{m_01_u:06x}")

            f.write(" ".join(parts) + "\n")


def write_params_pkg(path, n_vectors):
    content = f"""-- AUTO-GENERATED by moment_processor_generator.py. DO NOT EDIT BY HAND.

library ieee;
use ieee.std_logic_1164.all;

package moment_processor_test_params_pkg is
    constant TEST_N_VECTORS : natural := {n_vectors};
end package;
"""
    with open(path, 'w') as f:
        f.write(content)


def main():
    parser = argparse.ArgumentParser(
        description="Generate test vectors for moment_processor.vhd"
    )
    parser.add_argument("-n", "--num-random", type=int, default=1000,
                        help="Number of random test vectors (default: 1000)")
    parser.add_argument("-s", "--seed", type=int, default=0,
                        help="RNG seed (default: 0)")
    parser.add_argument("-o", "--output", type=str, default="moment_vectors.hex",
                        help="Output vector file (default: moment_vectors.hex)")
    parser.add_argument("--params-file", type=str,
                        default="moment_processor_test_params_pkg.vhd",
                        help="Auto-generated VHDL params package")
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)

    # Edge cases first
    patches_with_moments = []
    edge_cases = gen_edge_cases()
    print("Edge cases:")
    for name, patch in edge_cases:
        m_10, m_01 = compute_moments(patch)
        patches_with_moments.append((patch, m_10, m_01))
        print(f"  {name:25s}: m_10 = {m_10:8d}, m_01 = {m_01:8d}")

    # Random patches
    for _ in range(args.num_random):
        patch = rng.integers(0, 256, size=(PATCH_SIZE, PATCH_SIZE), dtype=np.uint8)
        m_10, m_01 = compute_moments(patch)
        patches_with_moments.append((patch, m_10, m_01))

    write_vector_file(args.output, patches_with_moments)
    write_params_pkg(args.params_file, len(patches_with_moments))

    n_total = len(patches_with_moments)
    print(f"\nWrote {n_total} vectors ({len(edge_cases)} edge cases + {args.num_random} random) "
          f"to {args.output}")
    print(f"Wrote test params to {args.params_file}")


if __name__ == "__main__":
    main()