"""Production-parameter pyramid test vectors for extractor_pyramid_tb.

Reproduces the real hardware scenario that the single-image extractor_top_tb
never covered: the 8 EuRoC-mono pyramid levels streamed back-to-back through ONE
extractor_top at MAX_WIDTH=752 (=> MAX_CELL_COLS=20, CCW=5, wide selection
grids), each level with its own cfg geometry and a reset between.

Emits ONE concatenated pixel file, ONE concatenated gated-keypoint file (level
order), and a params package with the per-level dimensions / grid / counts.

Each level is an INDEPENDENT dense image, so if the RTL leaks gate state across
levels (a bad inter-level reset), level N+1's output diverges from its
independent golden and the TB catches it.

Run from testbenches/:  py pyramid_tb_generator.py
"""

import numpy as np

from extractor_top_generator import (
    golden_keypoints, hx, compute_cell_grid, apply_strict_gate, select_per_cell,
)


def make_pyramid_dense_image(W, H, seed=0):
    """Grid of well-separated strict+permissive cluster pairs, tuned so each
    interior selection cell holds BOTH a strict and a permissive corner (the gate
    fires broadly) while the total corner count stays near the real EuRoC level-0
    ballpark (~6-7k) so nothing overflows the FIFO -> no drops -> clean exact
    match. Exercises the cellcol/band/strict_seen paths the 256-wide sim missed."""
    rng = np.random.default_rng(seed)
    img = np.full((H, W), 128, dtype=np.uint8)
    step = 40
    for y in range(20, H - 25, step):
        for x in range(20, W - 25, step):
            sval = 220 if rng.integers(0, 2) else 40            # strong -> strict corners
            img[y:y + 8, x:x + 8] = sval
            wval = 128 + (13 if rng.integers(0, 2) else -13)    # weak -> permissive corners
            img[y + 12:y + 20, x + 12:x + 20] = wval
    return img

# EuRoC mono resized pyramid (exactly the sizes from the hardware console logs).
LEVELS = [(600, 350), (500, 292), (417, 243), (347, 203),
          (289, 169), (241, 141), (201, 117), (167, 98)]
TH_PERM = 7
TH_STRICT = 20
MAX_WIDTH = 752   # production G_MAX_WIDTH -> CCW=5 (the path the 256-wide sim never hit)


def main():
    all_px, all_kps, meta = [], [], []
    for lvl, (W, H) in enumerate(LEVELS):
        img = make_pyramid_dense_image(W, H, seed=100 + lvl)
        grid = compute_cell_grid(W, H)
        full, _ = golden_keypoints(img, TH_PERM, TH_STRICT)
        gated, n_supp = apply_strict_gate(full, grid)

        # The invariant under test at PRODUCTION params: gate preserves the final set.
        ref = select_per_cell(full, W, H, grid)
        test = select_per_cell(gated, W, H, grid)
        if ref != test:
            only_ref = sorted(set(ref) - set(test))
            only_test = sorted(set(test) - set(ref))
            raise AssertionError(
                f"L{lvl} ({W}x{H}): gate broke select_per_cell equivalence -- "
                f"lost {only_ref[:8]}{'...' if len(only_ref) > 8 else ''}, "
                f"gained {only_test[:8]}{'...' if len(only_test) > 8 else ''}")

        all_px.append(img.reshape(-1))
        all_kps.append(gated)
        meta.append(dict(W=W, H=H, grid=grid, n=len(gated), n_supp=n_supp))
        print(f"L{lvl} {W}x{H}: wCell={grid['wCell']} hCell={grid['hCell']} "
              f"nCols={grid['nCols']} nRows={grid['nRows']} | full={len(full)} "
              f"gated={len(gated)} supp={n_supp} | equiv OK ({len(ref)})")

    with open("pyramid_pixels.hex", "w") as f:
        for px in all_px:
            f.write("\n".join(f"{int(v):02x}" for v in px) + "\n")

    # One expected file per score type (same corner set, different 32-bit
    # response column: FAST score zero-extended vs integer Harris response).
    for suffix, key in (("", "score"), ("_harris", "hresp")):
        with open(f"pyramid_expected{suffix}.txt", "w") as f:
            for kps in all_kps:
                for k in kps:
                    f.write(f"{k['x']} {k['y']} {k['score']} {k['is_brighter']} "
                            f"{k['passed_strict']} {hx(k['angle'], 24)} {k['tol']} "
                            f"{hx(k['m10'], 24)} {hx(k['m01'], 24)} {hx(k[key], 32)}\n")

    def arr(name, vals):
        return f"    constant {name} : nat_array := ({', '.join(str(v) for v in vals)});\n"

    with open("pyramid_test_params_pkg.vhd", "w") as f:
        f.write("-- AUTO-GENERATED by pyramid_tb_generator.py. DO NOT EDIT.\n\n"
                "package pyramid_test_params_pkg is\n"
                "    type nat_array is array (natural range <>) of natural;\n"
                f"    constant PYR_MAX_WIDTH : natural := {MAX_WIDTH};\n"
                f"    constant PYR_NLEVELS   : natural := {len(LEVELS)};\n"
                f"    constant PYR_TH_PERM   : natural := {TH_PERM};\n"
                f"    constant PYR_TH_STRICT : natural := {TH_STRICT};\n")
        f.write(arr("PYR_W",     [m['W'] for m in meta]))
        f.write(arr("PYR_H",     [m['H'] for m in meta]))
        f.write(arr("PYR_WCELL", [m['grid']['wCell'] for m in meta]))
        f.write(arr("PYR_HCELL", [m['grid']['hCell'] for m in meta]))
        f.write(arr("PYR_NCOLS", [m['grid']['nCols'] for m in meta]))
        f.write(arr("PYR_NROWS", [m['grid']['nRows'] for m in meta]))
        f.write(arr("PYR_NKP",   [m['n'] for m in meta]))
        f.write(arr("PYR_NSUPP", [m['n_supp'] for m in meta]))
        f.write("end package;\n")

    print(f"TOTAL gated={sum(m['n'] for m in meta)} suppressed={sum(m['n_supp'] for m in meta)}")
    print("Files: pyramid_pixels.hex, pyramid_expected.txt, pyramid_test_params_pkg.vhd")


if __name__ == "__main__":
    main()
